### ISSUE TITLE
Implement version of BetaCalibration with only one parameter a (a=b,m=0.5)

### ISSUE THREAD

**Issue by perellonieto** [betacal/python#1]
There are multiple versions of BetaCalibration with a different number of parameters:
- abm: all parameters are estimated
- ab: parameter m is fixed to 0.5 and a and b are estimated
- am: parameter b is fixed with the same value as a, and a and m are estimated

**Comment by perellonieto** [comment]
The commit f879d853b8341df4fe3fd4215e854b56d36e2691 in the branch feat_param_a has a initial version that needs to be revised and tested.

**Comment by perellonieto** [comment]
I see that the problem is that the line [307](https://github.com/betacal/python/blob/f879d853b8341df4fe3fd4215e854b56d36e2691/betacal/beta_calibration.py#L307) is only a placeholder to save the results, but it is not used later for the predictions. I was expecting the new _BetaCal to predict symetric functions but that is not the case.

I see that it is necessary that the LogisticRegression is fitted with equal variance on both classes. I am trying to find out how this is done.

**Comment by perellonieto** [comment]
Commit 67a6a7b solves the a = b problem, but the m does not seem to behave as an m=0.5

**Comment by simontindemans** [comment]
@perellonieto, I tried using the "a" option from the PyPi repository (``pip install betacal``), but it still has the bug fixed above. Can you merge the fix you implemented here? Is there still an issue with the ``m`` parameter?

**Comment by tmfilho** [comment]
Commit 124aefb8c2e8d124cf18a0a24755db2e93411e35 (now merged into master) solves these issues.
The new version will soon be available in PyPi (pip install betacal).

**Comment by tmfilho** [comment]
The new version (1.1.0) is already available through pip install betacal.
Thanks for the patience.
