### ISSUE TITLE
parameters = None

### ISSUE THREAD

**Issue by onacrame** [betacal/python#5]
When calling BetaCalibration(parameters="abm"), if I get_params, it shows parameters = None.  Additionally, if I use BetaCalibration in cross_val_score or cross_val_predict I get the following error message along the same lines:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-f8f9eac990c1> in <module>()
----> 1 scores = cross_val_score(bc,pred_target['Prediction'].values,pred_target['Target'].values, cv=kfold, scoring=log_loss2)

d:\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    400                                 fit_params=fit_params,
    401                                 pre_dispatch=pre_dispatch,
--> 402                                 error_score=error_score)
    403     return cv_results['test_score']
    404 

d:\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    238             return_times=True, return_estimator=return_estimator,
    239             error_score=error_score)
--> 240         for train, test in cv.split(X, y, groups))
    241 
    242     zipped_scores = list(zip(*scores))

d:\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self, iterable)
    981             # remaining jobs.
    982             self._iterating = False
--> 983             if self.dispatch_one_batch(iterator):
    984                 self._iterating = self._original_iterator is not None
    985 

d:\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in dispatch_one_batch(self, iterator)
    818             tasks = BatchedCalls(itertools.islice(iterator, batch_size),
    819                                  self._backend.get_nested_backend(),
--> 820                                  self._pickle_cache)
    821             if len(tasks) == 0:
    822                 # No more tasks available in the iterator: tell caller to stop.

d:\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __init__(self, iterator_slice, backend, pickle_cache)
    251 
    252     def __init__(self, iterator_slice, backend, pickle_cache=None):
--> 253         self.items = list(iterator_slice)
    254         self._size = len(self.items)
    255         self._backend = backend

d:\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in <genexpr>(.0)
    238             return_times=True, return_estimator=return_estimator,
    239             error_score=error_score)
--> 240         for train, test in cv.split(X, y, groups))
    241 
    242     zipped_scores = list(zip(*scores))

d:\Continuum\anaconda3\lib\site-packages\sklearn\base.py in clone(estimator, safe)
     61     for name, param in six.iteritems(new_object_params):
     62         new_object_params[name] = clone(param, safe=False)
---> 63     new_object = klass(**new_object_params)
     64     params_set = new_object.get_params(deep=False)
     65 

d:\Continuum\anaconda3\lib\site-packages\betacal\__init__.py in __init__(self, parameters)
     29             self.calibrator_ = _BetaABCal()
     30         else:
---> 31             raise ValueError('Unknown parameters', parameters)
     32 
     33     def fit(self, X, y, sample_weight=None):

ValueError: ('Unknown parameters', None)

**Comment by perellonieto** [comment]
I think that the __init__ requires the following line:

```
self.parameters = parameters
```

in order to be scikit-learn compilant, and be able to call get_params and set_params properly.

**Comment by tmfilho** [comment]
The new version (1.1.0) with the relevant fix is already available through pip install betacal.
Thanks for the patience.
